name: Laravel Tests

# Quando isso vai rodar?
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o seu código para a máquina virtual
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Prepara o PHP na máquina virtual
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Mude para a versão do seu projeto (8.1, 8.3, etc)
        extensions: mbstring, dom, fileinfo, sqlite3

    # 3. Copia o arquivo de ambiente
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # 4. Instala as dependências (a pasta vendor é criada AQUI e morre AQUI)
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # 5. Gera a chave da aplicação
    - name: Generate key
      run: php artisan key:generate

    # 6. Cria o banco de dados SQLite em memória (para ser rápido)
    - name: Create Database
      run: |
        touch database/database.sqlite
        
    # 7. Roda os testes
    - name: Execute tests (Unit and Feature tests)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test